### ISSUE TITLE
FR11: Users must be logged in to view certain content

### ISSUE THREAD

**Issue by bbrothers18** [WSU-4110/Learning-Pods#14]
|FR11: Users must be logged in to view certain content |
|---|
|**Goal**: A user must log in using their username and password in order to utilize the website.
**Stakeholders:** data admin|
| **Description:** In order to prevent users from accessing the functionality of the website without a profile, users must first either log in, or sign up with a personal profile before they are allowed access. Many features of the website can be previewed or will be described in detail from the homepage, however, the main functionality of the website requires a profile be created or used.|
| **Origin:** The team members came up with this functional requirement on the first meeting when creating the initial proposal for the project.|
| **Version:** 1.0  |  
|**Date:** 09/23/2020  
|  **Priority:** 1 |

**Comment by r-ghst** [comment]
I have added the option for the user to log out of their current session as they will be required to log in.
