### ISSUE TITLE
FR13:  Scheduling Meetings based on search results and matches

### ISSUE THREAD

**Issue by r-ghst** [WSU-4110/Learning-Pods#15]
|FR13:  Scheduling Meetings based on search results and matches|
|---|
|**Goal**: Generate a random and equal distribution of who host the meet ups within pods. |
**Stakeholders:** Users(parents and children), data admin, web admin |
| **Description:** Once a group is formed along with the days of the weeks they will meet and how often, there will be a random number generator that is applied to a random host for each group meet up for as long as the group meet ups occur. |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |  
|**Date:** 09/23/2020 |  
|  **Priority:** 3 |

**Comment by gs3935** [comment]
Currently working on this issue. Running into trouble with the initial forming of groups. Other than that, the files are about 80% done.

**Comment by gs3935** [comment]
Will upload some code by tomorrow or Saturday for Final Review, Deleted some mistakes from the previous commit
