### ISSUE TITLE
FR16: Home and School Profiles

### ISSUE THREAD

**Issue by gs3935** [WSU-4110/Learning-Pods#28]
|FR16:  Allow parents to enter information about their home and school|
|---|
|**Goal**: Allow parents to enter information about their home and school |
**Stakeholders:** Users(parents and children), data admin, web admin |
| **Description:** Allow parents to create a profile for their school or select one if it already exists. Also allow them to create a profile for their home that can work as a meeting host location. |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |  
|**Date:** 11/11/2020 |  
|  **Priority:** 2 |

**Comment by r-ghst** [comment]
Gathered data for all public schools in Michigan, k-12. The table provides an ID, name, address, city, grades covered, and zip code.

**Comment by r-ghst** [comment]
#30

**Comment by r-ghst** [comment]
Restructured previous school table and populated with all public schools in Michigan on 000webhost.

**Comment by r-ghst** [comment]
w/ @gs3935 collaborating how profiles can be structured filter search results based on school and results
