### ISSUE TITLE
NFR05: Privacy Policy

### ISSUE THREAD

**Issue by JackLacassee** [WSU-4110/Learning-Pods#3]
|NFR05.  Privacy Policy|
|---|
|**Goal**: Securely handle data, and achieve trust from users that data is being handled securely
**Stakeholders:** Users(parents and children), web admin|
| **Description:** Data given by users will not be given to third party companies; the data given by users to Learning Pods will be used for Learning Pods only. Personal user data can be deleted by the user at any time, allowing for data transparency and trust. All data given by users is stored appropriately and securely.  |
| **Origin:** The team members came up with this functional requirement on the first meeting when thinking of how users would want to feel safe using the app.|
| **Version:** 1.0  |  
|**Date:** 09/23/2020 
|  **Priority:** 3 |

**Comment by r-ghst** [comment]
Had privacy policy generated, but did not apply it yet.  Need to add a way to access it.

**Comment by r-ghst** [comment]
Applied a link to the privacy policy where ever the user is able to enter personal data (profile and sign up pages).
